export const SIDE_BAR_TOGGLE = "SIDE_BAR_TOGGLE";
export const LOADING_START = "LOADING_START";
export const LOADING_STOP = "LOADING_STOP";
export const ADMIN_LOADING_START = "ADMIN_LOADING_START";
export const ADMIN_LOADING_STOP = "ADMIN_LOADING_STOP";
